server:
  port: 8080
  servlet:
    context-path: /api
    session:
      timeout: PT60M


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.231.128:3306/rain?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: password
  main:
    allow-circular-references: true
  mail:
    protocol: smtp
    host: smtp.qq.com
    port: 587
    username: 2664067940@qq.com
    password:
    test-connection: false
    properties:
      mail:
        debug: true
        mine:
          splitlongparameters: false
        smtp:
          auth: false
        default-encoding: UTF-8

project:
  folder: D://untitled/bbs/
inner:
  api:
    appKey: easybbs
    appSecrcet: easybbs_key
isDev: true
admin:
  email: 2664067940@qq.com
  account: admin
  password: admin123
web:
  api:
    url: localhost:8080/api/innerApi/refresSysSetting
logging:
  level:
    com.example.mybatis_plus.sys.mapper: debug
mybatis:
  mapper-locations: classpath*:mybatis.mapper/*.xml


