server:
  port: 7070
  servlet:
    context-path: /api
    session:
      timeout: PT60M


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.130.120.42/rain?useSSL=false&serverTimezone=GMT
    username: root
    password: 123456
  main:
    allow-circular-references: true
  mail:
    protocol: smtp
    host: smtp.qq.com
    port: 587
    username: 2664067940@qq.com
    password: kqdchgesjhqrecea
    test-connection: false
    properties:
      mail:
        debug: true
        mine:
          splitlongparameters: false
        smtp:
          auth: false
        default-encoding: UTF-8

inner:
  api:
    appKey: easybbs
    appSecrcet: easybbs_key
admin:
  email: 2664067940@qq.com
  account: admin
  password: admin123
web:
  api:
    url: localhost:8080/api/innerApi/refresSysSetting
logging:
  level:
    com.example.mybatis_plus.sys.mapper: debug
mybatis:
  mapper-locations: classpath*:mybatis.mapper/*.xml


